#!/bin/sh
#  Copyright 2012 TripAdvisor, LLC
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
# Checks that there is no local mail
###############################################################################
# nagios variables

CRITICAL=2
WARNING=1
OK=0

test=LOCAL_MAIL

###############################################################################

mailspool=/var/spool/mail

if [[ ! -r $mailspool ]]; then
    echo "$test CRITICAL: Cannot read $mailspool"
    exit $CRITICAL
fi

if [[ ! -d $mailspool ]]; then
    echo "$test CRITICAL: $mailspool is not a directory"
    exit $CRITICAL
fi

bigfiles=$(find $mailspool -type f -size +0 -print)

if [[ -z "$bigfiles" ]];then
    echo "$test OK: No local mail"
    exit $OK
else
    echo "$test CRITICAL: Local mail in $bigfiles"
    exit $CRITICAL
fi
